// =============================================================================
// Test Document Registry, synthetic documents for import pipeline testing
// =============================================================================
//
// HIPAA INVARIANT: every name, date, address, phone, and SSN in these
// documents is fully synthetic. No real patient data is present. Each entity
// is chosen to exercise a specific category of the PII detection pipeline:
//
//   - PERSON (patient, family, officer, judge, examiner names)
//   - DATE_TIME (DOB, evaluation dates, incident dates)
//   - LOCATION (addresses, cities, states, correctional facilities)
//   - US_SSN (in fields that would realistically carry one)
//   - PHONE_NUMBER (practice and collateral phones)
//   - EMAIL_ADDRESS (attorney and practice emails)
//   - MEDICAL_RECORD_NUMBER (MRN, case number, docket)
//
// The content mimics real forensic documents in structure so the extracted
// text exercises the real pipeline, but the fictional nature is explicit in
// each document's opening line.
// =============================================================================

export type TestDocFormat = 'pdf' | 'docx' | 'txt' | 'rtf' | 'md' | 'csv'

export interface TestDocument {
  readonly id: string
  readonly title: string
  readonly author: string
  readonly format: TestDocFormat
  readonly category: 'referral' | 'collateral' | 'testing' | 'interview' | 'transcript'
  readonly body: string
  /** How many PHI entities the PII pipeline SHOULD detect. Used as a sanity bound in integration tests. */
  readonly expectedPhiCountAtLeast: number
}

const SYNTHETIC_NOTICE =
  '[SYNTHETIC TEST DOCUMENT. All names, dates, addresses, and identifiers in this document are fictitious. No real patient data is present. Generated by Psygil for import pipeline testing.]'

// ---------------------------------------------------------------------------
// Doc 1: Referral Letter (DOCX)
// ---------------------------------------------------------------------------

const REFERRAL_LETTER: TestDocument = {
  id: 'sample_referral_letter',
  title: 'Referral Letter - Vanmeter v. State',
  author: 'Margaret Tupper, Esq.',
  format: 'docx',
  category: 'referral',
  expectedPhiCountAtLeast: 8,
  body: `${SYNTHETIC_NOTICE}

TUPPER & ASSOCIATES
Criminal Defense
1847 Larimer Street, Suite 700
Denver, CO 80202
Phone: (303) 555-0184
Email: mtupper@tupperlaw.example

April 7, 2026

Dr. Jordan Whitfield, Psy.D., ABPP
Forensic Psychology Services
1234 Grant Street
Denver, CO 80203

RE: Wendell Vanmeter
    Case No. 2026-CR-3041
    Denver District Court, Division 4
    Honorable Rosalind Beckworth presiding

Dear Dr. Whitfield,

I represent Mr. Wendell Vanmeter in the above-referenced matter and write to request a forensic psychological evaluation on the question of competency to stand trial. Mr. Vanmeter was arrested on March 3, 2026 and charged with Aggravated Assault, Second Degree (C.R.S. 18-3-203). He is currently held without bond at the Denver County Jail.

Mr. Vanmeter was born on August 14, 1979. He reports a long history of paranoid ideation and auditory hallucinations that I have been unable to fully characterize in our attorney-client interviews. He has expressed confusion about the charging process and has repeatedly asked me whether the judge is "real or a recording." He has also refused to engage with plea discussions and has stated that "the District Attorney's office is reading my thoughts."

I am seeking your evaluation on the Dusky standard, specifically:
1. Whether Mr. Vanmeter has a rational and factual understanding of the proceedings against him.
2. Whether he has sufficient present ability to consult with counsel with a reasonable degree of rational understanding.

The court has authorized the evaluation and will expect a written report by May 5, 2026. I have included the arrest report, charging documents, and the jail mental health intake note.

Mr. Vanmeter has consented in writing to your review of his Denver Health Medical Center outpatient psychiatry records (MRN 4421906). The release is also enclosed.

Please contact my paralegal, Priya Sundararajan, at (303) 555-0191 to arrange jail access. The Denver County Jail requires 24 hours advance notice for professional visits.

Thank you for your assistance with this matter.

Sincerely,

Margaret Tupper, Esq.
Colorado Bar #24817`,
}

// ---------------------------------------------------------------------------
// Doc 2: Police Arrest Report (PDF)
// ---------------------------------------------------------------------------

const ARREST_REPORT: TestDocument = {
  id: 'sample_arrest_report',
  title: 'Arrest Report 2026-00147',
  author: 'Denver Police Department',
  format: 'pdf',
  category: 'collateral',
  expectedPhiCountAtLeast: 10,
  body: `${SYNTHETIC_NOTICE}

DENVER POLICE DEPARTMENT
Incident / Arrest Report

Report Number: DPD-2026-00147
Incident Date: March 3, 2026
Time of Dispatch: 22:47
Reporting Officer: Ofc. Daniel Halvorsen, Badge #7412
Secondary: Ofc. Teresa Ocampo, Badge #8102
District: District 6

SUBJECT INFORMATION
Name: Vanmeter, Wendell Cole
DOB: 08/14/1979
Address: 2219 Welton Street, Apt 4B, Denver, CO 80205
Phone: (720) 555-0127
Last Known Employer: Unemployed since approximately January 2024
Charges: C.R.S. 18-3-203 Aggravated Assault, Second Degree

NARRATIVE
On the above date and time, Officer Halvorsen and Officer Ocampo responded to a report of a disturbance at the 7-Eleven at 2100 Welton Street. Upon arrival officers observed a male subject, later identified as Wendell Vanmeter, pacing in the parking lot and shouting at no one visible. The store clerk, Bashir Kahlani, stated that the subject had entered the store approximately ten minutes earlier, grabbed a store employee by the shirt, and accused the employee of "broadcasting from the fluorescent lights." The clerk stated the subject did not steal anything and appeared to be in "some kind of episode."

Officers approached the subject with verbal commands. The subject initially complied and provided his name as Wendell Vanmeter. When officers attempted to detain the subject for questioning the subject pulled away, shouted "you're one of them too," and struck Officer Halvorsen once in the chest with a closed fist. Officer Ocampo assisted in the takedown. The subject was placed in handcuffs without further incident.

Officer Halvorsen was treated at the scene by Denver Health Paramedic Unit 14 for a minor contusion and declined transport. The subject was transported to the Denver Detention Center for booking.

STATEMENTS
Bashir Kahlani (clerk, witness): Statement taken at the scene. Mr. Kahlani stated the subject came in twice earlier in the day and bought coffee both times without incident. Mr. Kahlani described the subject as "a regular" and said this was the first time he had ever seen him act aggressively.

Wendell Vanmeter (arrestee): Declined to provide a statement. Was observed during transport to make several statements of the nature "they know I know" and "the cameras are counting." Transporting officer noted these in the vehicle log.

DISPOSITION
Subject booked at Denver Detention Center at 23:52 on 03/03/2026. Medical screening at booking noted subject "agitated, paranoid, disoriented to date and location, responding to internal stimuli." Subject was placed on Mental Health Watch pending psychiatric evaluation.

Reporting Officer: D. Halvorsen #7412
Shift Supervisor: Sgt. Monique Ouellette, #3398
Report Closed: 03/04/2026 02:14`,
}

// ---------------------------------------------------------------------------
// Doc 3: Collateral Records Cover Sheet (TXT)
// ---------------------------------------------------------------------------

const RECORDS_COVER_SHEET: TestDocument = {
  id: 'sample_records_cover_sheet',
  title: 'Medical Records Cover Sheet',
  author: 'Denver Health Medical Center',
  format: 'txt',
  category: 'collateral',
  expectedPhiCountAtLeast: 6,
  body: `${SYNTHETIC_NOTICE}

DENVER HEALTH MEDICAL CENTER
Health Information Management
777 Bannock Street
Denver, CO 80204
Phone: (303) 555-0220
Fax: (303) 555-0221

RELEASE OF INFORMATION COVER SHEET

Patient: Vanmeter, Wendell C.
MRN: 4421906
DOB: 08/14/1979

Requestor: Dr. Jordan Whitfield, Psy.D.
           Forensic Psychology Services
           1234 Grant Street
           Denver, CO 80203

Date of Request: April 8, 2026
Authorization on File: Yes (signed 04/05/2026)
Scope of Release: Psychiatric outpatient records, 01/01/2022 to present

Records Enclosed:
1. Intake assessment dated 02/12/2022 (Dr. Anoushka Ramamurthy)
2. Treatment plan dated 02/12/2022, revised 09/04/2022
3. Progress notes: 12 encounters from 02/12/2022 through 11/18/2024
4. Medication administration history 01/01/2022 to 03/01/2026
5. Discharge summary dated 11/18/2024 (last contact)

Documents Excluded from This Release:
- Psychotherapy notes (separate authorization required per 45 CFR 164.508)
- Substance use disorder records (separate authorization per 42 CFR Part 2)

This release is governed by HIPAA and the minimum necessary standard. Questions about scope may be directed to HIM at the number above.

Released by: Carolyn Odysseus, RHIT
Date: April 9, 2026`,
}

// ---------------------------------------------------------------------------
// Doc 4: Psychological Test Report (RTF)
// ---------------------------------------------------------------------------

const TEST_REPORT: TestDocument = {
  id: 'sample_test_report',
  title: 'MMPI-3 Score Report',
  author: 'Pearson Clinical Assessments',
  format: 'rtf',
  category: 'testing',
  expectedPhiCountAtLeast: 4,
  body: `${SYNTHETIC_NOTICE}

MMPI-3 SCORE REPORT

Examinee: Vanmeter, Wendell C.
Examinee ID: 2026-CR-3041
Age: 46
Education: 14 years
Date of Testing: April 12, 2026
Examiner: Jordan Whitfield, Psy.D., ABPP

VALIDITY SCALES

Cannot Say (CNS): 2 items
Variable Response Inconsistency (VRIN-r): T = 53
True Response Inconsistency (TRIN-r): T = 51F (true bias)
Infrequent Responses (F-r): T = 68
Infrequent Psychopathology Responses (Fp-r): T = 74
Infrequent Somatic Responses (Fs): T = 52
Symptom Validity (FBS-r): T = 55
Response Bias Scale (RBS): T = 57
Uncommon Virtues (L-r): T = 42
Adjustment Validity (K-r): T = 38

Interpretation: The validity pattern suggests the examinee responded to the items with adequate consistency. Elevations on F-r and Fp-r are moderate and likely reflect genuine severe psychopathology rather than feigning, particularly in light of unremarkable symptom validity measures. Low K-r suggests limited defensiveness.

HIGHER-ORDER SCALES

Emotional/Internalizing Dysfunction (EID): T = 72
Thought Dysfunction (THD): T = 79
Behavioral/Externalizing Dysfunction (BXD): T = 54

RESTRUCTURED CLINICAL SCALES

Demoralization (RCd): T = 66
Somatic Complaints (RC1): T = 58
Low Positive Emotions (RC2): T = 71
Cynicism (RC3): T = 55
Antisocial Behavior (RC4): T = 57
Ideas of Persecution (RC6): T = 80
Dysfunctional Negative Emotions (RC7): T = 68
Aberrant Experiences (RC8): T = 75
Hypomanic Activation (RC9): T = 48

CLINICAL INTERPRETATION

The profile is marked by significant elevations on scales associated with thought dysfunction, persecutory ideation, and aberrant perceptual experiences. The pattern is consistent with an active psychotic presentation and warrants immediate consideration of a primary psychotic disorder. Low positive emotion and demoralization elevations suggest a concurrent depressive component.

This report is a computer-generated interpretation and is not a diagnostic conclusion. Final diagnostic determinations require integration of test data with clinical interview, behavioral observation, and collateral information.`,
}

// ---------------------------------------------------------------------------
// Doc 5: Clinical Interview Notes (MD)
// ---------------------------------------------------------------------------

const INTERVIEW_NOTES: TestDocument = {
  id: 'sample_interview_notes',
  title: 'Clinical Interview Notes',
  author: 'Jordan Whitfield, Psy.D.',
  format: 'md',
  category: 'interview',
  expectedPhiCountAtLeast: 7,
  body: `${SYNTHETIC_NOTICE}

# Clinical Interview Notes

**Examiner:** Jordan Whitfield, Psy.D., ABPP
**Examinee:** Wendell C. Vanmeter
**DOB:** 08/14/1979
**Case:** 2026-CR-3041
**Date of Interview:** April 10, 2026
**Location:** Denver County Jail, Attorney-Client Room 3
**Duration:** 2 hours 15 minutes

## Notice

Mr. Vanmeter was advised at the outset that this evaluation was court-ordered at the request of his attorney Ms. Tupper and that the usual doctor-patient confidentiality does not apply. He was told a written report would be shared with his attorney, the court, and the prosecution. He acknowledged understanding and agreed to proceed.

## Appearance and Behavior

Mr. Vanmeter appeared his stated age. He was wearing jail-issued orange attire, was adequately groomed, and had mild hand tremor. He was seated throughout the interview and displayed occasional restlessness. He made limited eye contact and at times appeared to scan the upper corners of the room.

## Speech and Language

Speech was of normal rate and volume but demonstrated occasional loose associations. He used several idiosyncratic phrases ("thought-printing," "the channel bleeds through") that he did not elaborate on despite clarification requests.

## Mood and Affect

Mr. Vanmeter described his mood as "tired and watched." Affect was constricted but congruent with reported mood. He denied current suicidal or homicidal ideation and denied any intent to harm himself or others.

## Thought Process and Content

Thought process was tangential and at times illogical, particularly when discussing his legal situation. He expressed persistent delusions of reference (he believed that news broadcasts were about him), delusions of thought broadcasting, and paranoid ideation focused on the District Attorney's office. He denied command hallucinations but endorsed hearing "two voices that argue about me" intermittently over the past three years.

## Perception

Auditory hallucinations as noted above. He denied current visual, olfactory, or tactile hallucinations.

## Cognition

Oriented to person and year. He was unsure of the exact date and month. He was aware he was in a jail but did not know which jail. He recalled 2 of 3 words after five minutes. Attention was fair. Concentration was mildly impaired on serial sevens.

## Insight and Judgment

Insight into the nature of his illness was limited. He endorsed having "had problems" in the past but did not describe these as mental illness and stated his current symptoms were "not the same thing." Judgment regarding the legal process was impaired.

## Legal Understanding Probes

Mr. Vanmeter was able to name the judge (correctly identified as Judge Beckworth). When asked about the role of the judge, he stated "she decides if the DA keeps filming me." He correctly identified the prosecutor as "the DA" but described the DA's role as "trying to keep the broadcast going." He named his attorney as Ms. Tupper and stated she "is supposed to help me but she might not be real." He was not able to correctly identify the roles of the jury or the potential consequences of conviction.

## Plan

Administer MMPI-3, ECST-R, and collateral review. Consider rescheduling for a second session after two weeks of jail psychiatric services to assess change.`,
}

// ---------------------------------------------------------------------------
// Doc 6: Interview Transcript (TXT), short sample
// ---------------------------------------------------------------------------

const INTERVIEW_TRANSCRIPT: TestDocument = {
  id: 'sample_interview_transcript',
  title: 'Interview Transcript Excerpt',
  author: 'Psygil Transcription',
  format: 'txt',
  category: 'transcript',
  expectedPhiCountAtLeast: 5,
  body: `${SYNTHETIC_NOTICE}

CLINICAL INTERVIEW TRANSCRIPT (EXCERPT)
Examinee: Wendell Vanmeter
Examiner: Dr. Jordan Whitfield
Date: April 10, 2026
Location: Denver County Jail

[00:12:04]
EXAMINER: Mr. Vanmeter, can you tell me why you think you're here today?
VANMETER: Which here? The building here or the inside-my-head here?
EXAMINER: Let's start with the building.
VANMETER: This is the jail. They put me here after the Seven-Eleven thing.
EXAMINER: What happened at the store?
VANMETER: The lights started reading me. I told the guy to turn them off. He wouldn't do it. I pushed him. I'm not a violent person.

[00:18:30]
EXAMINER: Has this happened to you before? The lights?
VANMETER: Not the lights exactly. Different things. The phone when I had one. The car radio. It's been going on for years. My sister used to notice. She's in Tucson now. Her name is Coralee.
EXAMINER: When did Coralee first notice?
VANMETER: About six years ago. She tried to get me to go to the place on Bannock but I didn't trust the doctor. His name was Dr. Ramamurthy. I went twice.

[00:23:45]
EXAMINER: What do you know about why you're in court?
VANMETER: They charged me with assault. Aggravated assault, second degree. Ms. Tupper told me that. She's my lawyer.
EXAMINER: Do you understand what that charge means?
VANMETER: It means I hit him. But I only pushed him. I don't think that's assault.
EXAMINER: What happens if you go to trial?
VANMETER: A jury decides. But I don't think there's a real jury. I think they're actors. The whole courthouse might be a set.

[END OF EXCERPT at 00:31:12]`,
}

// ---------------------------------------------------------------------------
// Doc 7: School Records Summary (CSV)
// ---------------------------------------------------------------------------

const SCHOOL_RECORDS: TestDocument = {
  id: 'sample_school_records',
  title: 'School Records Summary',
  author: 'Tucson Unified School District',
  format: 'csv',
  category: 'collateral',
  expectedPhiCountAtLeast: 5,
  body: `# ${SYNTHETIC_NOTICE}
# Tucson Unified School District - Cumulative Record Summary
# Student: Vanmeter, Wendell Cole
# DOB: 08/14/1979
# Released to: Dr. Jordan Whitfield, Psy.D. per signed authorization dated 04/05/2026
Year,Grade,School,Teacher,GPA,Attendance,BehaviorNotes
1989-1990,5,Drachman Elementary,Louise Benoit,3.2,96%,None
1990-1991,6,Mansfeld Middle,Hector Villalobos,3.1,94%,None
1991-1992,7,Mansfeld Middle,Patricia Esquerra,2.8,89%,Occasional inattention
1992-1993,8,Mansfeld Middle,Terrance Hackett,2.9,91%,None
1993-1994,9,Tucson High,Ingrid Palmgren,2.7,85%,Fatigue noted by 3 teachers
1994-1995,10,Tucson High,Raul Benitez,2.5,78%,Two absences unexcused
1995-1996,11,Tucson High,Loretta Sinkfield,2.1,72%,Referred to counselor Ms. Hadley
1996-1997,12,Tucson High,Raul Benitez,1.8,65%,Did not complete senior year
# Notes:
# Student transferred out January 1997; did not return for second semester.
# No special education services provided during enrollment.
# GED obtained through Pima Community College in 1999 per student self-report.
`,
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const TEST_DOCUMENTS: readonly TestDocument[] = [
  REFERRAL_LETTER,
  ARREST_REPORT,
  RECORDS_COVER_SHEET,
  TEST_REPORT,
  INTERVIEW_NOTES,
  INTERVIEW_TRANSCRIPT,
  SCHOOL_RECORDS,
] as const
