/**
 * Hard Rule scanner, enforces CLAUDE.md HARD RULE:
 *   Zero em dashes, zero en dashes, zero AI artifacts or watermarks.
 *
 * Throws on first violation with an actionable message. Intended to be
 * called from unit tests and from a pre-publish IPC guard.
 */

const FORBIDDEN_CODEPOINTS: readonly { readonly cp: string; readonly char: string }[] = [
  { cp: 'U+2014', char: '\u2014' }, // em dash
  { cp: 'U+2013', char: '\u2013' }, // en dash
]

const FORBIDDEN_WATERMARKS: readonly RegExp[] = [
  /generated by ai/i,
  /generated by claude/i,
  /co[- ]?authored by claude/i,
  /anthropic noreply/i,
  /generated with \[claude/i,
]

export interface ScanOptions {
  readonly label?: string
}

export function scanForProhibited(input: string, opts: ScanOptions = {}): void {
  const label = opts.label ? ` (${opts.label})` : ''
  for (const { cp, char } of FORBIDDEN_CODEPOINTS) {
    const idx = input.indexOf(char)
    if (idx !== -1) {
      const ctx = extractContext(input, idx)
      throw new Error(`HARD RULE violation${label}: ${cp} found at offset ${idx}. Context: "${ctx}"`)
    }
  }
  for (const pat of FORBIDDEN_WATERMARKS) {
    const m = pat.exec(input)
    if (m) {
      throw new Error(`HARD RULE violation${label}: AI watermark string detected: "${m[0]}"`)
    }
  }
}

function extractContext(s: string, idx: number, radius = 24): string {
  const start = Math.max(0, idx - radius)
  const end = Math.min(s.length, idx + radius)
  return s.slice(start, end).replace(/\s+/g, ' ')
}
