import { describe, it, expect } from 'vitest'
import { scanForProhibited } from '../../harness/hardRuleScan'

describe('HARD RULE scan', () => {
  it('accepts plain ASCII', () => {
    expect(() => scanForProhibited('hello, world')).not.toThrow()
  })

  it('rejects em dash (U+2014)', () => {
    expect(() => scanForProhibited('hello\u2014world')).toThrow(/U\+2014/)
  })

  it('rejects en dash (U+2013)', () => {
    expect(() => scanForProhibited('pages 1\u20132')).toThrow(/U\+2013/)
  })

  it('rejects AI watermark strings', () => {
    expect(() => scanForProhibited('Generated by AI')).toThrow(/watermark/i)
    expect(() => scanForProhibited('Co-authored by Claude')).toThrow(/watermark/i)
  })

  it('includes label in error message', () => {
    expect(() => scanForProhibited('x\u2014y', { label: 'report.docx' })).toThrow(/report\.docx/)
  })
})
