#!/usr/bin/env bash
set -euo pipefail

# Shared library for psygil-sync.sh
# Exports utility functions for locking, logging, safety gates, and git operations.

readonly PSYGIL_LOG_DIR="${HOME}/.psygil"
readonly PSYGIL_LOG_FILE="${PSYGIL_LOG_DIR}/sync.log"
readonly SYNC_LOCK_DIR="/tmp/psygil-sync.lock"

# Ensure log directory exists
mkdir -p "$PSYGIL_LOG_DIR"

# Get current git repo root
git_root() {
  git rev-parse --show-toplevel 2>/dev/null || echo "."
}

# Get current branch name
current_branch() {
  git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "HEAD"
}

# Get current commit SHA (short)
current_sha() {
  git rev-parse --short HEAD 2>/dev/null || echo "unknown"
}

# Get idle time in seconds (macOS only; Linux/Windows return 0)
idle_seconds() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    local result
    result=$(ioreg -c IOHIDSystem 2>/dev/null | awk '/HIDIdleTime/ {print int($NF/1000000000); exit}')
    result=$(echo "$result" | xargs)  # Trim whitespace
    echo "${result:-0}"
  else
    echo 0
  fi
}

# Check if current branch is protected (main/master)
is_protected_branch() {
  local branch
  branch="$(current_branch)"
  [[ "$branch" == "main" || "$branch" == "master" ]]
}

# Scan staged changes for forbidden characters and strings
# Returns 0 if clean, non-zero if violations found
hard_rule_scan_staged() {
  local violations=0
  local staged_diff

  # Get the staged diff
  staged_diff=$(git diff --cached --color=never 2>/dev/null || echo "")

  # Check for em dash (U+2014)
  if echo "$staged_diff" | grep -q $'\u2014'; then
    echo "ERROR: staged changes contain em dash (U+2014)"
    violations=$((violations + 1))
  fi

  # Check for en dash (U+2013)
  if echo "$staged_diff" | grep -q $'\u2013'; then
    echo "ERROR: staged changes contain en dash (U+2013)"
    violations=$((violations + 1))
  fi

  # Check for AI watermark strings
  if echo "$staged_diff" | grep -qiE "(Generated by AI|Co-authored by Claude|noreply@anthropic)"; then
    echo "ERROR: staged changes contain AI watermark strings"
    violations=$((violations + 1))
  fi

  return $violations
}

# Scan staged changes with gitleaks
# Returns 0 if clean or gitleaks not installed, non-zero if secrets found
gitleaks_scan_staged() {
  if ! command -v gitleaks &> /dev/null; then
    echo "WARN: gitleaks not installed; skipping secret scan"
    return 0
  fi

  if gitleaks protect --staged --verbose --redact 2>&1; then
    return 0
  else
    return 1
  fi
}

# Acquire lock via mkdir (atomic)
# Returns 0 on success, 1 if already locked
acquire_lock() {
  if mkdir "$SYNC_LOCK_DIR" 2>/dev/null; then
    return 0
  else
    return 1
  fi
}

# Release lock
release_lock() {
  rm -rf "$SYNC_LOCK_DIR" 2>/dev/null || true
}

# Append a JSON log entry
# append_log <action> <result> <message>
append_log() {
  local action="$1"
  local result="$2"
  local message="$3"
  local timestamp
  local branch
  local sha

  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  branch="$(current_branch)"
  sha="$(current_sha)"

  # Escape message for JSON
  message=$(printf '%s\n' "$message" | sed 's/\\/\\\\/g; s/"/\\"/g')

  # Append JSON line
  printf '{"timestamp":"%s","branch":"%s","sha":"%s","action":"%s","result":"%s","message":"%s"}\n' \
    "$timestamp" "$branch" "$sha" "$action" "$result" "$message" >> "$PSYGIL_LOG_FILE"
}

# Get number of uncommitted tracked files
uncommitted_count() {
  local count
  count=$(git diff --name-only 2>/dev/null | wc -l)
  echo "$count" | tr -d ' '
}

# Get count of commits ahead of origin
ahead_count() {
  local count
  count=$(git rev-list --count @{u}..HEAD 2>/dev/null || echo 0)
  echo "$count" | tr -d ' '
}

# Get count of commits behind origin
behind_count() {
  local count
  count=$(git rev-list --count HEAD..@{u} 2>/dev/null || echo 0)
  echo "$count" | tr -d ' '
}

# Check if there are uncommitted changes (tracked or untracked)
has_uncommitted_changes() {
  [[ -n "$(git status --porcelain 2>/dev/null)" ]]
}

# Check if there are uncommitted tracked changes only
has_tracked_changes() {
  [[ -n "$(git diff --name-only 2>/dev/null)" ]]
}

# Get time (in seconds) since last commit
seconds_since_last_commit() {
  local last_commit_time
  local now

  last_commit_time=$(git log -1 --format=%ct 2>/dev/null || echo 0)
  now=$(date +%s)

  if [[ "$last_commit_time" == "0" ]]; then
    echo "0"
  else
    echo $((now - last_commit_time))
  fi
}

# Stage only tracked files (respects .gitignore)
stage_tracked_changes() {
  git add -u 2>/dev/null || true
}

# Create a commit with the given message
# create_commit <message>
create_commit() {
  local message="$1"

  if ! has_tracked_changes; then
    append_log "commit" "skipped" "no tracked changes to commit"
    return 0
  fi

  stage_tracked_changes

  if ! hard_rule_scan_staged; then
    append_log "commit" "failed" "HARD RULE violations detected"
    git reset 2>/dev/null || true
    return 1
  fi

  if ! gitleaks_scan_staged; then
    append_log "commit" "failed" "gitleaks detected secrets"
    git reset 2>/dev/null || true
    return 1
  fi

  git commit -m "$message" 2>/dev/null || true
  append_log "commit" "success" "$message"
  return 0
}

# Push current branch to origin (with branch protection)
# Returns 0 on success or skip, 1 on error
push_to_origin() {
  if is_protected_branch; then
    append_log "push" "skipped" "branch protection: cannot auto-push main/master"
    return 0
  fi

  local ahead
  ahead=$(ahead_count)

  if [[ "$ahead" -eq 0 ]]; then
    append_log "push" "skipped" "no commits ahead of origin"
    return 0
  fi

  local branch
  branch="$(current_branch)"

  if git push origin "$branch" 2>&1 | tee /tmp/psygil-push.log; then
    append_log "push" "success" "pushed $ahead commit(s)"
    return 0
  else
    append_log "push" "failed" "push failed; see logs"
    return 1
  fi
}

# Format seconds as human-readable string
format_duration() {
  local seconds
  seconds=$(echo "$1" | tr -d ' ')
  if [[ -z "$seconds" ]]; then
    echo "0s"
    return
  fi
  if [[ $seconds -lt 60 ]]; then
    echo "${seconds}s"
  elif [[ $seconds -lt 3600 ]]; then
    echo "$((seconds / 60))m"
  else
    echo "$((seconds / 3600))h"
  fi
}
