/**
 * Hard Rule scanner (production module), enforces the CLAUDE.md HARD RULE:
 *   Zero em dashes (U+2014), zero en dashes (U+2013), zero AI artifacts
 *   or watermarks.
 *
 * Two entry points:
 *   scanForProhibited(input, opts): throws HardRuleViolationError on first
 *     violation. Use from pre-publish gates that must abort on any hit.
 *   findProhibited(input, opts): returns an array of violations (possibly
 *     empty). Use when reporting multiple issues to a UI or when scanning
 *     a batch of generated documents before deciding whether to block.
 *
 * The scanner is used by:
 *   src/main/reports/index.ts (pre-publish gate, per doc 31 G14)
 *   src/main/agents/runner.ts (post-Claude agent output guard, per plan A.6)
 *   app/tests/harness/hardRuleScan.ts (test re-export, unchanged behavior)
 */

const FORBIDDEN_CODEPOINTS: readonly { readonly cp: string; readonly char: string; readonly label: string }[] = [
  { cp: 'U+2014', char: '\u2014', label: 'em dash' },
  { cp: 'U+2013', char: '\u2013', label: 'en dash' },
]

const FORBIDDEN_WATERMARKS: readonly RegExp[] = [
  /generated by ai/i,
  /generated by claude/i,
  /co[- ]?authored by claude/i,
  /anthropic noreply/i,
  /generated with \[claude/i,
]

export interface ScanOptions {
  /** Human-readable tag attached to violation messages (e.g. a file path). */
  readonly label?: string
}

export interface HardRuleViolation {
  /** Either a unicode codepoint like "U+2014" or a literal watermark string. */
  readonly rule: string
  /** Human-readable category description for UI. */
  readonly category: 'em_dash' | 'en_dash' | 'ai_watermark'
  /** Zero-based offset within the scanned string where the hit starts. */
  readonly offset: number
  /** A small excerpt around the hit, whitespace-collapsed. */
  readonly context: string
  /** The caller-supplied label (file path or section name), if any. */
  readonly label?: string
}

export class HardRuleViolationError extends Error {
  readonly violation: HardRuleViolation

  constructor(violation: HardRuleViolation) {
    const labelSuffix = violation.label ? ` (${violation.label})` : ''
    const ruleDescription =
      violation.category === 'ai_watermark'
        ? `AI watermark detected: "${violation.rule}"`
        : `${violation.rule}`
    super(
      `HARD RULE violation${labelSuffix}: ${ruleDescription} at offset ${violation.offset}. Context: "${violation.context}"`,
    )
    this.name = 'HardRuleViolationError'
    this.violation = violation
  }
}

/**
 * Throw on first HARD RULE violation. Existing tests rely on this behavior.
 */
export function scanForProhibited(input: string, opts: ScanOptions = {}): void {
  const all = findProhibited(input, opts)
  if (all.length > 0) {
    throw new HardRuleViolationError(all[0])
  }
}

/**
 * Return every HARD RULE violation in `input`, in order of occurrence.
 * Returns an empty array if the input is clean.
 */
export function findProhibited(input: string, opts: ScanOptions = {}): readonly HardRuleViolation[] {
  const violations: HardRuleViolation[] = []

  for (const { cp, char, label } of FORBIDDEN_CODEPOINTS) {
    let from = 0
    while (from < input.length) {
      const idx = input.indexOf(char, from)
      if (idx === -1) break
      violations.push({
        rule: cp,
        category: label === 'em dash' ? 'em_dash' : 'en_dash',
        offset: idx,
        context: extractContext(input, idx),
        label: opts.label,
      })
      from = idx + 1
    }
  }

  for (const pat of FORBIDDEN_WATERMARKS) {
    const re = new RegExp(pat.source, pat.flags.includes('g') ? pat.flags : pat.flags + 'g')
    let match: RegExpExecArray | null
    while ((match = re.exec(input)) !== null) {
      violations.push({
        rule: match[0],
        category: 'ai_watermark',
        offset: match.index,
        context: extractContext(input, match.index),
        label: opts.label,
      })
      if (match.index === re.lastIndex) re.lastIndex++
    }
  }

  return violations.sort((a, b) => a.offset - b.offset)
}

function extractContext(s: string, idx: number, radius = 24): string {
  const start = Math.max(0, idx - radius)
  const end = Math.min(s.length, idx + radius)
  return s.slice(start, end).replace(/\s+/g, ' ')
}
