#!/usr/bin/env node
/**
 * CI-friendly HARD RULE scanner. Walks the source tree and fails on any
 * U+2014, U+2013, or AI watermark string in user-facing content.
 *
 *   app/src/**         (renderer + main source, excluding tests)
 *   docs/**            (everything)
 *
 * Intentionally avoids node_modules, dist, build, and the tests tree.
 */

const { readFileSync, readdirSync, statSync } = require('fs')
const { join, extname } = require('path')

const ROOTS = [
  join(__dirname, '..', 'src'),
  join(__dirname, '..', '..', 'docs'),
]

const SKIP_DIRS = new Set(['node_modules', 'dist', 'build', '.git', 'out', 'test-results', 'coverage'])
const TEXT_EXT = new Set(['.ts', '.tsx', '.js', '.jsx', '.md', '.html', '.css', '.json', '.txt', '.yml', '.yaml'])

const FORBIDDEN_CHARS = [
  { cp: 'U+2014', char: '\u2014' },
  { cp: 'U+2013', char: '\u2013' },
]
const FORBIDDEN_PATTERNS = [
  /generated by ai/i,
  /generated by claude/i,
  /co[- ]?authored by claude/i,
  /anthropic noreply/i,
]

let violations = 0

function walk(dir) {
  let entries
  try { entries = readdirSync(dir) } catch { return }
  for (const name of entries) {
    if (SKIP_DIRS.has(name)) continue
    const full = join(dir, name)
    let s
    try { s = statSync(full) } catch { continue }
    if (s.isDirectory()) { walk(full); continue }
    if (!TEXT_EXT.has(extname(full))) continue
    scanFile(full)
  }
}

function scanFile(path) {
  const content = readFileSync(path, 'utf-8')
  for (const { cp, char } of FORBIDDEN_CHARS) {
    const idx = content.indexOf(char)
    if (idx !== -1) {
      const line = content.slice(0, idx).split('\n').length
      console.error(`[HARD RULE] ${cp} at ${path}:${line}`)
      violations++
    }
  }
  for (const pat of FORBIDDEN_PATTERNS) {
    const m = pat.exec(content)
    if (m) {
      const line = content.slice(0, m.index).split('\n').length
      console.error(`[HARD RULE] watermark "${m[0]}" at ${path}:${line}`)
      violations++
    }
  }
}

for (const r of ROOTS) walk(r)

if (violations > 0) {
  console.error(`\n${violations} HARD RULE violations. See CLAUDE.md.`)
  process.exit(1)
}
console.log('HARD RULE scan clean.')
